// -*- C++ -*- generated by wxGlade 0.6.5 (standalone edition) on Wed Apr 03 12:02:22 2013
#pragma once
#ifndef PLAYERDROPPED_H
#define PLAYERDROPPED_H

class CDroppedValuePlayer: public wxDialog
{
public:
    CDroppedValuePlayer(wxWindow* parent, const std::vector<CPlayer> *player, int condition);
	void OnOKUIUpdate(wxUpdateUIEvent &event);
	wxString GetDroppedPlayerName();
	int GetDroppedPlayerValue();

protected:
    void set_properties();
    void do_layout();

private:
	std::vector<CPlayer> m_players;
	int m_condition;
	wxPanel *m_panel;
	wxStaticText *m_label1, *m_label2;
    wxListBox* m_playersList;
	wxSpinCtrl *m_newValue;
	wxButton *m_ok;
}; // wxGlade: end class

#endif // PLAYERDROPPED_H
